# Generated by Django 4.1.1 on 2022-10-19 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id_accesorio', models.IntegerField(primary_key=True, serialize=False)),
                ('accesorio', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ACCESORIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CARGO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=45)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'CLIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoContrato',
            fields=[
                ('id_estado_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_contrato', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ESTADO_CONTRATO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoHab',
            fields=[
                ('id_estado_hab', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_hab', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ESTADO_HAB',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado_p', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ESTADO_PEDIDO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id_estado_user', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_user', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ESTADO_USUARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('subtotal', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'db_table': 'FACTURA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FamiliaProd',
            fields=[
                ('id_familia_p', models.IntegerField(primary_key=True, serialize=False)),
                ('familia_p', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'FAMILIA_PROD',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('num_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('id_estado_hab_h', models.ForeignKey(blank=True, db_column='id_estado_hab_h', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.estadohab')),
            ],
            options={
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'HABITACION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id_minuta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'MINUTA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'PLATO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=200)),
                ('rubro', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'PROVEEDOR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoCama',
            fields=[
                ('id_tipo_cama', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_cama', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TIPO_CAMA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id_tipo_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'TIPO_CONTRATO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoHab',
            fields=[
                ('id_tipo_hab', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_hab', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'TIPO_HAB',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id_tipo_plato', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_plato', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'TIPO_PLATO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoProd',
            fields=[
                ('id_tipo_prod', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_prod', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TIPO_PROD',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('tipo_usuario', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('pwd', models.CharField(max_length=45)),
                ('id_estado_u', models.ForeignKey(blank=True, db_column='id_estado_u', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.estadousuario')),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SkuProducto',
            fields=[
                ('id_sku', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.IntegerField(db_column='SKU')),
                ('fecha_venc', models.IntegerField()),
                ('id_familia_s', models.ForeignKey(db_column='id_familia_s', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.familiaprod')),
                ('id_tipo_producto_s', models.ForeignKey(db_column='id_tipo_producto_s', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.tipoprod')),
            ],
            options={
                'db_table': 'SKU_PRODUCTO',
                'managed': True,
                'unique_together': {('id_sku', 'id_familia_s', 'id_tipo_producto_s')},
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=100)),
                ('id_factura_s', models.ForeignKey(blank=True, db_column='id_factura_s', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.factura')),
            ],
            options={
                'db_table': 'SERVICIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_venc', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('id_plato_p', models.ForeignKey(blank=True, db_column='id_plato_p', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.plato')),
                ('id_sku_p', models.ForeignKey(blank=True, db_column='id_sku_p', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.skuproducto')),
            ],
            options={
                'db_table': 'PRODUCTO',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='plato',
            name='id_tipo_plato_p',
            field=models.ForeignKey(db_column='id_tipo_plato_p', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.tipoplato'),
        ),
        migrations.CreateModel(
            name='PlatMin',
            fields=[
                ('id_plat_min', models.IntegerField(primary_key=True, serialize=False)),
                ('id_min_pm', models.ForeignKey(blank=True, db_column='id_min_pm', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.minuta')),
                ('id_plat_pm', models.ForeignKey(blank=True, db_column='id_plat_pm', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.plato')),
            ],
            options={
                'db_table': 'PLAT_MIN',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('num_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('id_estado_p_o', models.ForeignKey(blank=True, db_column='id_estado_p_o', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.estadopedido')),
                ('id_proveedor_o', models.ForeignKey(blank=True, db_column='id_proveedor_o', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Pedidos',
                'db_table': 'ORDEN_PEDIDO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('num_orden', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('id_huesped', models.IntegerField()),
                ('nombre_huesped', models.CharField(max_length=200)),
                ('id_factura', models.IntegerField()),
                ('id_cliente_o', models.ForeignKey(blank=True, db_column='id_cliente_o', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.cliente')),
            ],
            options={
                'verbose_name_plural': 'Ordenes De Compra',
                'db_table': 'ORDEN_COMPRA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id_huesped', models.AutoField(primary_key=True, serialize=False)),
                ('rut_huesped', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=100)),
                ('p_apellido', models.CharField(max_length=100)),
                ('s_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=45)),
                ('id_cliente_h', models.IntegerField()),
                ('id_minuta_h', models.ForeignKey(blank=True, db_column='id_minuta_h', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.minuta')),
                ('num_habitacion_h', models.ForeignKey(blank=True, db_column='num_habitacion_h', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.habitacion')),
                ('num_orden_h', models.ForeignKey(blank=True, db_column='num_orden_h', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.ordencompra')),
            ],
            options={
                'verbose_name_plural': 'Huespedes',
                'db_table': 'HUESPED',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='id_tipo_cama_h',
            field=models.ForeignKey(blank=True, db_column='id_tipo_cama_h', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.tipocama'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='id_tipo_hab_h',
            field=models.ForeignKey(db_column='id_tipo_hab_h', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.tipohab'),
        ),
        migrations.CreateModel(
            name='HabAcc',
            fields=[
                ('id_hab_acc', models.IntegerField(primary_key=True, serialize=False)),
                ('id_acc_ha', models.ForeignKey(blank=True, db_column='id_acc_ha', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.accesorio')),
                ('id_hab_ha', models.ForeignKey(blank=True, db_column='id_hab_ha', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.habitacion')),
            ],
            options={
                'db_table': 'HAB_ACC',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='num_orden_f',
            field=models.ForeignKey(blank=True, db_column='num_orden_f', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.ordencompra'),
        ),
        migrations.CreateModel(
            name='DetFactura',
            fields=[
                ('id_det_factura', models.AutoField(primary_key=True, serialize=False)),
                ('monto_t', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('id_factura_d', models.ForeignKey(blank=True, db_column='id_factura_d', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.factura')),
            ],
            options={
                'db_table': 'DET_FACTURA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cant_huesp', models.IntegerField()),
                ('id_estado_contrato_c', models.ForeignKey(blank=True, db_column='id_estado_contrato_c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.estadocontrato')),
                ('id_tipo_contrato_c', models.ForeignKey(blank=True, db_column='id_tipo_contrato_c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.tipocontrato')),
            ],
            options={
                'verbose_name_plural': 'Contratos',
                'db_table': 'CONTRATO',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_contrato_c',
            field=models.ForeignKey(blank=True, db_column='id_contrato_c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.contrato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_usuario_c',
            field=models.ForeignKey(blank=True, db_column='id_usuario_c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.usuario'),
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id_cama', models.IntegerField(primary_key=True, serialize=False)),
                ('cant_cojines', models.IntegerField()),
                ('id_tipo_cama_c', models.ForeignKey(blank=True, db_column='id_tipo_cama_c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.tipocama')),
            ],
            options={
                'db_table': 'CAMA',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='plato',
            unique_together={('id_plato', 'id_tipo_plato_p')},
        ),
        migrations.AlterUniqueTogether(
            name='habitacion',
            unique_together={('num_habitacion', 'id_tipo_hab_h')},
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empleado', models.CharField(max_length=45)),
                ('nombre_empleado', models.CharField(max_length=45)),
                ('p_apellido', models.CharField(max_length=45)),
                ('s_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(max_length=45)),
                ('fono', models.CharField(max_length=45)),
                ('id_cargo_e', models.ForeignKey(db_column='id_cargo_e', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.cargo')),
                ('id_usuario_e', models.ForeignKey(blank=True, db_column='id_usuario_e', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.usuario')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'EMPLEADO',
                'managed': True,
                'unique_together': {('id_empleado', 'id_cargo_e')},
            },
        ),
    ]
