# Generated by Django 4.1.1 on 2022-10-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id_accesorio', models.IntegerField(primary_key=True, serialize=False)),
                ('accesorio', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ACCESORIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id_cama', models.IntegerField(primary_key=True, serialize=False)),
                ('cant_cojines', models.IntegerField()),
            ],
            options={
                'db_table': 'CAMA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CARGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=45)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cant_huesp', models.IntegerField()),
            ],
            options={
                'db_table': 'CONTRATO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empleado', models.CharField(max_length=45)),
                ('nombre_empleado', models.CharField(max_length=45)),
                ('p_apellido', models.CharField(max_length=45)),
                ('s_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(max_length=45)),
                ('fono', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'EMPLEADO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoContrato',
            fields=[
                ('id_estado_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_contrato', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ESTADO_CONTRATO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoHab',
            fields=[
                ('id_estado_hab', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_hab', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ESTADO_HAB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado_p', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ESTADO_PEDIDO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id_estado_user', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_user', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ESTADO_USUARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('subtotal', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
            ],
            options={
                'db_table': 'FACTURA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamiliaProd',
            fields=[
                ('id_familia_p', models.IntegerField(primary_key=True, serialize=False)),
                ('familia_p', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'FAMILIA_PROD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('num_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'HABITACION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id_huesped', models.AutoField(primary_key=True, serialize=False)),
                ('rut_huesped', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=100)),
                ('p_apellido', models.CharField(max_length=100)),
                ('s_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=45)),
                ('id_cliente_h', models.IntegerField()),
            ],
            options={
                'db_table': 'HUESPED',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id_minuta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'MINUTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('num_orden', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('id_huesped', models.IntegerField()),
                ('nombre_huesped', models.CharField(max_length=200)),
                ('id_factura', models.IntegerField()),
            ],
            options={
                'db_table': 'ORDEN_COMPRA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('num_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ORDEN_PEDIDO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'PLATO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venc', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
            ],
            options={
                'db_table': 'PRODUCTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=80)),
                ('rubro', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'PROVEEDOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SERVICIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkuProducto',
            fields=[
                ('id_sku', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.IntegerField(db_column='SKU')),
                ('fecha_venc', models.IntegerField()),
            ],
            options={
                'db_table': 'SKU_PRODUCTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCama',
            fields=[
                ('id_tipo_cama', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_cama', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TIPO_CAMA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id_tipo_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'TIPO_CONTRATO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoHab',
            fields=[
                ('id_tipo_hab', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_hab', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'TIPO_HAB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id_tipo_plato', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_plato', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'TIPO_PLATO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProd',
            fields=[
                ('id_tipo_prod', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_prod', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TIPO_PROD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=45)),
                ('tipo_usuario', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('pwd', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': False,
            },
        ),
    ]
