# Generated by Django 4.1.1 on 2022-10-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_hostal", "0003_alter_accesorio_options_alter_cama_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="producto", name="id_plato_p",),
        migrations.AddField(
            model_name="plato",
            name="id_producto_p",
            field=models.ForeignKey(
                blank=True,
                db_column="id_producto_p",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="admin_hostal.producto",
            ),
        ),
    ]
