# Generated by Django 4.1.1 on 2022-10-23 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hostal', '0004_remove_producto_id_plato_p_plato_id_producto_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_contrato_c',
            field=models.ForeignKey(blank=True, db_column='id_contrato_c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.contrato', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_usuario_c',
            field=models.ForeignKey(blank=True, db_column='id_usuario_c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(max_length=100, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut_empresa',
            field=models.CharField(max_length=45, verbose_name='Rut Empresa'),
        ),
    ]
