# Generated by Django 4.1.1 on 2022-10-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hostal', '0005_alter_cliente_id_contrato_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='id_cliente_h',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_hostal.cliente'),
        ),
    ]
