# Generated by Django 4.1.1 on 2022-10-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
