# Generated by Django 4.1.1 on 2022-10-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rut_empresa",
                    models.CharField(
                        help_text="Rut de Empresa", max_length=45, unique=True
                    ),
                ),
                ("nombre_empresa", models.CharField(max_length=100)),
                ("razon_social", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("telefono", models.IntegerField()),
                ("direccion", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Clientes", "db_table": "CLIENTE",},
        ),
    ]
