# Generated by Django 4.1.1 on 2022-10-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'verbose_name_plural': 'Clientes'},
        ),
    ]
