# Generated by Django 4.1.1 on 2022-10-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='CLIENTE',
        ),
    ]
