# Generated by Django 4.1.1 on 2022-10-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("huesped", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="huesped", options={"verbose_name_plural": "Huespedes"},
        ),
    ]
