# Generated by Django 4.1.1 on 2022-10-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huesped', '0002_alter_huesped_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huesped',
            options={'managed': False, 'verbose_name_plural': 'Huespedes'},
        ),
    ]
