# Generated by Django 4.1.1 on 2022-10-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huesped', '0003_alter_huesped_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Huesped',
        ),
    ]
