# Generated by Django 4.1.1 on 2022-10-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("estado", models.BooleanField(default=True)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
                ("fechaModificacion", models.DateTimeField(auto_now=True)),
                ("id_empleado", models.AutoField(primary_key=True, serialize=False)),
                ("rut_empleado", models.CharField(max_length=45)),
                ("nombre_empleado", models.CharField(max_length=45)),
                ("p_apellido", models.CharField(max_length=45)),
                ("s_apellido", models.CharField(blank=True, max_length=45, null=True)),
                ("email", models.CharField(max_length=45)),
                ("fono", models.CharField(max_length=45)),
            ],
            options={"db_table": "EMPLEADO", "managed": False,},
        ),
    ]
