# Generated by Django 4.1.1 on 2022-10-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("id_empleado", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rut_empleado",
                    models.CharField(
                        help_text="Rut de Empleado", max_length=45, unique=True
                    ),
                ),
                ("nombre_empleado", models.CharField(max_length=45)),
                ("p_apellido", models.CharField(max_length=45)),
                ("s_apellido", models.CharField(blank=True, max_length=45, null=True)),
                ("email", models.CharField(max_length=45)),
                ("fono", models.CharField(max_length=45)),
            ],
            options={"verbose_name_plural": "Empleado", "db_table": "EMPLEADO",},
        ),
    ]
