# Generated by Django 4.1.1 on 2022-10-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
