# Generated by Django 4.1.1 on 2022-10-06 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name_plural': 'Clientes'},
        ),
    ]
