# Generated by Django 4.1.1 on 2022-10-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False, 'verbose_name_plural': 'Empleados'},
        ),
    ]
