# Generated by Django 4.1.1 on 2022-10-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_empleado_usuariocrea_empleado_usuariomodifica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name_plural': 'Empleado'},
        ),
    ]
