# Generated by Django 4.1 on 2022-09-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hostal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='Direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='Email',
            field=models.CharField(max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='Nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='Telefono',
            field=models.CharField(max_length=100, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Rubro',
            field=models.CharField(max_length=100, null=True, verbose_name='Rubro'),
        ),
    ]
