# Generated by Django 4.1 on 2022-09-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hostal', '0002_proveedor_direccion_proveedor_email_proveedor_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='Rubro',
            new_name='rubro',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='Telefono',
            new_name='telefono',
        ),
    ]
