# Generated by Django 4.1 on 2022-09-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hostal', '0003_rename_direccion_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='id',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
