# Generated by Django 4.1 on 2022-09-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hostal', '0004_remove_proveedor_id_proveedor_id_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre',
            new_name='nombre_prov',
        ),
    ]
