# Generated by Django 4.1 on 2022-09-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hostal', '0005_rename_nombre_proveedor_nombre_prov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('rut_cli', models.CharField(max_length=100, null=True, verbose_name='Rut')),
                ('nombre_cli', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('razon_social', models.CharField(max_length=100, null=True, verbose_name='Razón Social')),
                ('email_cli', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('telefono_cli', models.CharField(max_length=100, null=True, verbose_name='Telefono')),
                ('direccion_cli', models.CharField(max_length=100, null=True, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_emp', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('pri_apell_emp', models.CharField(max_length=100, null=True, verbose_name='Primer Apellido')),
                ('seg_apell_emp', models.CharField(max_length=100, null=True, verbose_name='Segundo Apellido')),
                ('email_emp', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('telefono_emp', models.CharField(max_length=100, null=True, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id_hue', models.AutoField(primary_key=True, serialize=False)),
                ('rut_hue', models.CharField(max_length=100, null=True, verbose_name='Rut')),
                ('nombre_hue', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('pri_apell_hue', models.CharField(max_length=100, null=True, verbose_name='Primer Apellido')),
                ('seg_apell_hue', models.CharField(max_length=100, null=True, verbose_name='Segundo Apellido')),
                ('email_hue', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('telefono_hue', models.CharField(max_length=100, null=True, verbose_name='Telefono')),
                ('direccion_prov', models.CharField(max_length=100, null=True, verbose_name='Direccion')),
            ],
        ),
    ]
