# Generated by Django 4.1 on 2022-09-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hostal', '0006_cliente_empleado_huesped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huesped',
            old_name='direccion_prov',
            new_name='direccion_hue',
        ),
        migrations.AddField(
            model_name='huesped',
            name='cliente_hue',
            field=models.CharField(max_length=100, null=True, verbose_name='Cliente'),
        ),
    ]
